#!/usr/bin/env bash
set -eo pipefail

dist_dir=${1-"_dist"}
env_path=${2-".env"}

dist_dir_absolute=`pwd`/$dist_dir
env_path_absolute=`pwd`/$env_path

echo "Writing dist files to: $dist_dir_absolute"
[[ -d "$dist_dir_absolute" ]] || mkdir -v "$dist_dir_absolute"

[[ `ls "$dist_dir_absolute" | wc -l` == 0 ]] || {
  echo "Destination dist directory must be empty" >&2
  exit 1
}

[[ -f "$env_path_absolute" ]] || {
  echo ".env file is missing" >&2
  exit 1
}

docker build -t txstreet .
docker run --rm \
  --mount type=bind,src="$dist_dir_absolute",dst=/home/node/app/dist \
  --mount type=bind,src="$env_path_absolute",dst=/home/node/app/.env,ro \
  txstreet
